### PR TITLE
Backport upstream changes to date

### PR DESCRIPTION
**Pull request by rdesgroppes**
This is to backport upstream changes:
- https://github.com/HubSpot/jackson-datatype-protobuf/pull/86
- https://github.com/HubSpot/jackson-datatype-protobuf/pull/88
- https://github.com/HubSpot/jackson-datatype-protobuf/pull/79
- https://github.com/HubSpot/jackson-datatype-protobuf/pull/93
- https://github.com/HubSpot/jackson-datatype-protobuf/pull/94

Practically, the change consists in:
1. merging upstream `master` branch to the present fork,
2. favoring upstream conventions (imports, indents) in files with merge conflicts,
3. bump versions from 0.9.13-x/0.9.14-x to 0.9.15-x.

:bulb: diff ignoring whitespaces: https://github.com/pragmaplatform/jackson-datatype-protobuf/pull/3/files?diff=unified&w=1

### CODE REVIEW

**Comment by rdesgroppes** [comment]
@chomey Would you be so kind as to review this PR, please?

**Comment by chomey** [comment]
Hi @rdesgroppes, my team is not looking to support this, and purely meant to keep it open as an example on how we solved the problem. Would recommend you fork the repo and merge it yourself, thanks.

**Comment by rdesgroppes** [comment]
> Hi @rdesgroppes, my team is not looking to support this, and purely meant to keep it open as an example on how we solved the problem. Would recommend you fork the repo and merge it yourself, thanks.

Fair enough, I'll do my best to contribute to the upstream repo, then.

**Comment by rdesgroppes** [comment]
Hi @chomey, just to let you know that the upstream repo received a renewed attention and addressed most of the reasons that made you fork. A version got just released with a better canonical serialization support, see: https://github.com/HubSpot/jackson-datatype-protobuf/releases/tag/jackson-datatype-protobuf-0.9.14

**Comment by chomey** [comment]
Thanks so much for informing me @rdesgroppes! I'm going to get my team cutover to using that today =)

**Pull request closed without merging**
